"""add service check models

Revision ID: 30f31933e3b1
Revises: 3edc45d7827e
Create Date: 2026-06-18 06:54:38.826717

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30f31933e3b1'
down_revision: Union[str, Sequence[str], None] = '3edc45d7827e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vm_id', sa.Integer(), nullable=False),
    sa.Column('service_name', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=True),
    sa.Column('check_command', sa.String(length=500), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['vm_id'], ['vms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_configs_id'), 'service_configs', ['id'], unique=False)
    op.create_index(op.f('ix_service_configs_vm_id'), 'service_configs', ['vm_id'], unique=False)
    op.create_table('service_statuses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vm_id', sa.Integer(), nullable=False),
    sa.Column('service_name', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('checked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['vm_id'], ['vms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_statuses_id'), 'service_statuses', ['id'], unique=False)
    op.create_index(op.f('ix_service_statuses_vm_id'), 'service_statuses', ['vm_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_index(op.f('ix_service_statuses_vm_id'), table_name='service_statuses')
    op.drop_index(op.f('ix_service_statuses_id'), table_name='service_statuses')
    op.drop_table('service_statuses')
    op.drop_index(op.f('ix_service_configs_vm_id'), table_name='service_configs')
    op.drop_index(op.f('ix_service_configs_id'), table_name='service_configs')
    op.drop_table('service_configs')
    # ### end Alembic commands ###
