"""add custom intervals

Revision ID: 3edc45d7827e
Revises: 003
Create Date: 2026-06-17 05:09:40.546106

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3edc45d7827e'
down_revision: Union[str, Sequence[str], None] = '003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_alerts_vm_sent_type', table_name='alerts')
    op.drop_index('idx_alerts_sent_at', table_name='alerts')
    op.create_index('idx_alerts_sent_at', 'alerts', ['sent_at'], unique=False, postgresql_ops={'sent_at': 'DESC'})
    op.drop_constraint('credentials_vm_id_key', 'credentials', type_='unique')
    op.drop_index('idx_credentials_vm_auth', table_name='credentials')
    op.drop_index('idx_metrics_timestamp', table_name='metrics')
    op.create_index('idx_metrics_timestamp', 'metrics', ['timestamp'], unique=False, postgresql_ops={'timestamp': 'DESC'})
    op.drop_index('idx_metrics_vm_timestamp', table_name='metrics')
    op.create_index('idx_metrics_vm_timestamp', 'metrics', ['vm_id', 'timestamp'], unique=False, postgresql_ops={'timestamp': 'DESC'})
    op.drop_index('idx_ping_results_timestamp', table_name='ping_results')
    op.create_index('idx_ping_results_timestamp', 'ping_results', ['timestamp'], unique=False, postgresql_ops={'timestamp': 'DESC'})
    op.drop_index('idx_users_email', table_name='users')
    op.drop_index('idx_users_username', table_name='users')
    op.add_column('vms', sa.Column('ping_interval_minutes', sa.Integer(), server_default='5', nullable=False))
    op.add_column('vms', sa.Column('dns_interval_hours', sa.Integer(), server_default='6', nullable=False))
    op.add_column('vms', sa.Column('ping_last_checked', sa.DateTime(timezone=True), nullable=True))
    op.drop_index('idx_vms_user_reachable', table_name='vms')
    op.drop_index('idx_vms_user_updated', table_name='vms')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_vms_user_updated', 'vms', ['user_id', sa.text('updated_at DESC')], unique=False)
    op.create_index('idx_vms_user_reachable', 'vms', ['user_id', 'is_reachable'], unique=False)
    op.drop_column('vms', 'ping_last_checked')
    op.drop_column('vms', 'dns_interval_hours')
    op.drop_column('vms', 'ping_interval_minutes')
    op.create_index('idx_users_username', 'users', ['username'], unique=False)
    op.create_index('idx_users_email', 'users', ['email'], unique=False)
    op.drop_index('idx_ping_results_timestamp', table_name='ping_results', postgresql_ops={'timestamp': 'DESC'})
    op.create_index('idx_ping_results_timestamp', 'ping_results', [sa.text('timestamp DESC')], unique=False)
    op.drop_index('idx_metrics_vm_timestamp', table_name='metrics', postgresql_ops={'timestamp': 'DESC'})
    op.create_index('idx_metrics_vm_timestamp', 'metrics', ['vm_id', sa.text('timestamp DESC')], unique=False)
    op.drop_index('idx_metrics_timestamp', table_name='metrics', postgresql_ops={'timestamp': 'DESC'})
    op.create_index('idx_metrics_timestamp', 'metrics', [sa.text('timestamp DESC')], unique=False)
    op.create_index('idx_credentials_vm_auth', 'credentials', ['vm_id', 'auth_type'], unique=False)
    op.create_unique_constraint('credentials_vm_id_key', 'credentials', ['vm_id'])
    op.drop_index('idx_alerts_sent_at', table_name='alerts', postgresql_ops={'sent_at': 'DESC'})
    op.create_index('idx_alerts_sent_at', 'alerts', [sa.text('sent_at DESC')], unique=False)
    op.create_index('idx_alerts_vm_sent_type', 'alerts', ['vm_id', sa.text('sent_at DESC'), 'alert_type'], unique=False)
    # ### end Alembic commands ###
