"""add_uptime_daily_summary

Revision ID: 7878722ef41a
Revises: 30f31933e3b1
Create Date: 2026-06-18 12:27:53.465877

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7878722ef41a'
down_revision: Union[str, Sequence[str], None] = '30f31933e3b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('uptime_daily_summaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vm_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('total_checks', sa.Integer(), nullable=False),
    sa.Column('successful_checks', sa.Integer(), nullable=False),
    sa.Column('avg_latency_ms', sa.Float(), nullable=True),
    sa.Column('max_latency_ms', sa.Float(), nullable=True),
    sa.Column('min_latency_ms', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['vm_id'], ['vms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vm_id', 'date', name='unique_vm_daily_summary')
    )
    op.create_index(op.f('ix_uptime_daily_summaries_date'), 'uptime_daily_summaries', ['date'], unique=False)
    op.create_index(op.f('ix_uptime_daily_summaries_id'), 'uptime_daily_summaries', ['id'], unique=False)
    op.create_index(op.f('ix_uptime_daily_summaries_vm_id'), 'uptime_daily_summaries', ['vm_id'], unique=False)
    op.drop_index('idx_alerts_sent_at', table_name='alerts')
    op.create_index('idx_alerts_sent_at', 'alerts', ['sent_at'], unique=False, postgresql_ops={'sent_at': 'DESC'})
    op.drop_index('idx_metrics_timestamp', table_name='metrics')
    op.create_index('idx_metrics_timestamp', 'metrics', ['timestamp'], unique=False, postgresql_ops={'timestamp': 'DESC'})
    op.drop_index('idx_metrics_vm_timestamp', table_name='metrics')
    op.create_index('idx_metrics_vm_timestamp', 'metrics', ['vm_id', 'timestamp'], unique=False, postgresql_ops={'timestamp': 'DESC'})
    op.drop_index('idx_ping_results_timestamp', table_name='ping_results')
    op.create_index('idx_ping_results_timestamp', 'ping_results', ['timestamp'], unique=False, postgresql_ops={'timestamp': 'DESC'})
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_ping_results_timestamp', table_name='ping_results', postgresql_ops={'timestamp': 'DESC'})
    op.create_index('idx_ping_results_timestamp', 'ping_results', [sa.text('timestamp DESC')], unique=False)
    op.drop_index('idx_metrics_vm_timestamp', table_name='metrics', postgresql_ops={'timestamp': 'DESC'})
    op.create_index('idx_metrics_vm_timestamp', 'metrics', ['vm_id', sa.text('timestamp DESC')], unique=False)
    op.drop_index('idx_metrics_timestamp', table_name='metrics', postgresql_ops={'timestamp': 'DESC'})
    op.create_index('idx_metrics_timestamp', 'metrics', [sa.text('timestamp DESC')], unique=False)
    op.drop_index('idx_alerts_sent_at', table_name='alerts', postgresql_ops={'sent_at': 'DESC'})
    op.create_index('idx_alerts_sent_at', 'alerts', [sa.text('sent_at DESC')], unique=False)
    op.drop_index(op.f('ix_uptime_daily_summaries_vm_id'), table_name='uptime_daily_summaries')
    op.drop_index(op.f('ix_uptime_daily_summaries_id'), table_name='uptime_daily_summaries')
    op.drop_index(op.f('ix_uptime_daily_summaries_date'), table_name='uptime_daily_summaries')
    op.drop_table('uptime_daily_summaries')
    # ### end Alembic commands ###
